### PR TITLE
Fantasy Football (Quay)

### PR DESCRIPTION
**Pull request by quaydragon**

### CODE REVIEW

**Comment by robertness** [comment]
Hi @quaydragon,
Please create a README.md file.  Please see other projects for reference.  Also, please remove the MP4 from the branch, upload it Youtube or another host, and add the link to the README file.

Also, put the files in a `/projects/fantasy_football/quay_approach` directory.

**Review by jypark0 — COMMENTED** [review]
Hi Quay, a couple comments:
- I had trouble getting `pymc3` and its dependency`theano` working. Please create a google colab or a conda `environment.yml` file (regular pip doesn't work well with `pycm3`).
- None of the plots are shown in the notebook. Use `plt.show()` or some other juptyer magic command.

**Comment by quaydragon** [comment]
Hi - not very good at github. Going to try my best here. Here is the link to the collab notebook:

https://colab.research.google.com/drive/1b8IarxD6pIfzBJQtlRhLo55DPnEvU0ky

**Comment by quaydragon** [comment]
I think it should be all set! Thank you.

**Review by jypark0 — APPROVED** [review]
I'll merge and make some remaining changes to the repo.

**Pull request merged**
