### PR TITLE
SCM Normalizing Flows (Google Cartoon Dataset)

### PR DESCRIPTION
**Pull request by sslakkimsetty**
This project the implementation on using Normalizing Flows for constructing SCMs to model image data. Specifically, we use Google's Cartoon Faces dataset.

### CODE REVIEW

**Review by robertness — COMMENTED** [review]
This is fantastic work!  Did you forget to include a video explainer?

**Comment by vartikatewari** [comment]
> This is fantastic work! Did you forget to include a video explainer?

Hi Robert, We have added the link to the video in the README file.

**Comment by sslakkimsetty** [comment]
Just posting the video link for accessibility: https://youtu.be/GfQtKxPfAOU

**Comment by robertness** [comment]
Hi @sslakkimsetty could you please remove the `.DS_Store` files from the file directory?

**Review by robertness — COMMENTED** [review]
@sslakkimsetty please remove these blank CSV lines. Here is an example of the issue https://github.com/altdeep/probmodeler/pull/6/files#diff-f4c0e7778cf2eb528c230b6f88cbc53de59c67038a532f148b3909cee291247eR102-R140

Also, when you see the symbol 🚫 it means you should add a newline to the bottom of the file.
image

**Review by jypark0 — CHANGES_REQUESTED** [review]
Hi Sai, I got an error running [CS7290-normalizing-flows-SCM.ipynb](https://github.com/sslakkimsetty/probmodeler/blob/261a46d69925a5d2b31295c65a7703867d365e7f/projects/SCM-normalizing-flows/notebook/CS7290-normalizing-flows-SCM.ipynb):
Screen Shot 2021-08-22 at 1 01 53 PM
And the relevant line:
Screen Shot 2021-08-22 at 1 03 06 PM
Could you check the notebook again?

**Comment by sslakkimsetty** [comment]
Hi John, I have also added the notebook for approach 1 (https://bit.ly/3sDNQzH). This code is fully runnable and shows output results. Our intended approach (approach 2) is fully implemented and the optimized training is still being worked upon. Both of the notebooks are present in (projects/SCM-normalizing-flows/notebook) directory.

**Review by jypark0 — APPROVED** [review]
Everything looks good, I can run approach 1. I'll go ahead and merge

**Pull request merged**
