### PR TITLE
Bayesian Media Mix Modeling

### PR DESCRIPTION
**Pull request by mianzhang39**

### CODE REVIEW

**Comment by mianzhang39** [comment]
Hi Professor,

I didn't see any projects folder in the probmodeler repo so I put my folder into tutorial folder without being aware of discussions in the forum..... Sorry about that.

But I was still not able to merge because it is said that 'This branch has no conflicts with the base branch. Only those with write access to this repository can merge pull requests.'

You can find my project if you have any issues: 
https://github.com/mianzhang39/CS7290-Project

**Review by robertness — COMMENTED** [review]
Hi Mian.  This is looking good.  Please create a /projects/BayesianMMM directory on this branch and move this to that directory.  When we merge your directory will be created.

**Comment by mianzhang39** [comment]
Hi Professor, 

Now there are two commits, and I think the second is what you wanna me do. But I don't know whether the first commit need to be deleted or not.

**Review by jypark0 — COMMENTED** [review]
Hi Mian, a couple comments:
- I had trouble installing the dependencies. You should consider creating a colab or a conda `environment.yml` (regular pip didn't work well for `pymc3` because of the `theano` dependency).
- I couldn't run your code because of the non-disclosure agreement. Besides that everything looks good.

**Comment by mianzhang39** [comment]
Hi John,

I just updated my submission as following:
1. Created a new folder called 'pictures' to contain all screenshots, which is suggested by Professor.
2. Updated the Setup section of README file, and add environment.yml as well as requirements.txt.
2. Add a new Jupyter Notebook started with '(Reproducible)', which reads data from two fake datasets.

**Comment by mianzhang39** [comment]
4. Move datasets to data folder, which is also suggested by Professor.

**Review by jypark0 — APPROVED** [review]
Great, everything looks good. I'll go ahead and merge.

**Pull request merged**
