### PR TITLE
Bayesian Fantasy Football (Ian)

### PR DESCRIPTION
**Pull request by iandardik**

### CODE REVIEW

**Review by robertness — COMMENTED** [review]
Hi Ian
Please change 

*  your home directory from "projects/ian_fantasy_football" to "projects/fantasy_football/dardick_model"
* Remove the "cs7290" from the file names

**Review by jypark0 — COMMENTED** [review]
Hi Ian, I can run both notebooks without errors. Please incorporate the changes and I will merge your code.

**Comment by iandardik** [comment]
Just updated my project with the requested changes.  Thanks!  - Ian

**Review by jypark0 — APPROVED** [review]
Everything looks good, I'll go ahead and merge

**Pull request merged**
