### PR TITLE
Multitarget Tracking

### PR DESCRIPTION
**Pull request by kstisser**
Here is my Multitarget Tracking final. I've included all 4 Jupyter Notebooks, as well as my 5 minute intro to the topic. I added the Plate Diagram as requested. Please let me know if you need anything else.

### CODE REVIEW

**Comment by robertness** [comment]
Hi Karissa,
Just one request.  Would you please remove the MP4 from the branch, upload to Youtube or some such, and then add it as a link to the README.md?

**Review by jypark0 — CHANGES_REQUESTED** [review]
Hi Karissa, a couple of comments.
- Please take out the mp4 file and create a link to the video in `README.md`
- I get an error in for `num_spurious=dist.Poisson...` in `generate_data()`. This happens because the rate parameter of the Poisson `=0`. Just change `args.expected_num_spurious` to  be `> 0`

**Comment by kstisser** [comment]
I removed the video, and posted privately to youtube, and added Robert Ness's gmail to share. I think I resolved the bug John mentioned. Let me know if there are any other issues.

**Comment by jypark0** [comment]
Closing for PR #8

**Pull request closed without merging**
